resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: 298301037019.dkr.ecr.us-west-2.amazonaws.com/trustbuilder/trustbuilder
  newTag: 0.0.2
