# permissions for end users to view certificatepackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificatepackage-viewer-role
rules:
- apiGroups:
  - trustbuilder.directv.com
  resources:
  - certificatepackages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trustbuilder.directv.com
  resources:
  - certificatepackages/status
  verbs:
  - get
