# permissions for end users to edit certificatepackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificatepackage-editor-role
rules:
- apiGroups:
  - trustbuilder.directv.com
  resources:
  - certificatepackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trustbuilder.directv.com
  resources:
  - certificatepackages/status
  verbs:
  - get
